name: TP E2E Tests

on:
  push:
    paths:
      - /**
  create:
  pull_request:
    paths:
      - /**
    types: [ opened, reopened, edited, synchronize ]

jobs:
  E2E_tests:
    runs-on: ubuntu-latest
    services:
      hub:
        image: selenium/hub
        ports:
          - 4444:4444
      chrome:
        image: selenium/node-chrome
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: traffic_ops
          POSTGRES_PASSWORD: twelve
          POSTGRES_DB: traffic_ops
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@master
      - name: todb
        id: todb
        uses: ./.github/actions/todb-init
      - name: Run TP
        uses: ./.github/actions/tp-e2e-tests
#      - run: npm i -g protractor
#      - run: protractor conf.js
#        working-directory: traffic_portal/test/end_to_end

