name: TP E2E Tests

on:
  push:
    paths:
      - /**
  create:
  pull_request:
    paths:
      - /**
    types: [ opened, reopened, edited, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name:
        uses: ./.github/actions/tp-e2e-tests
