name: TP E2E Tests

on:
  push:
    paths:
      - traffic_portal/**
  create:
  pull_request:
    paths:
      - traffic_portal/**
    types: [ opened, reopened, edited, synchronize ]

jobs:
  E2E_tests:
    runs-on: ubuntu-latest

    env:
      SELENIUM_HUB_HOST: hub,
      TEST_HOST: testHost

    container:
      image: node:12.18
      options: --network-alias testHost

    services:
      hub:
        image: selenium/hub
      chrome:
        image: selenium/node-chrome
        env:
          HUB_HOST: hub
          HUB_PORT: 4444

    steps:
      - uses: actions/checkout@master
      - run: npm i -g protractor
      - run: protractor conf.js
        working-directory: traffic_portal/test/end_to_end

