name: TP E2E Tests

on:
  push:
    paths:
      - traffic_portal/**
  create:
  pull_request:
    paths:
      - traffic_portal/**
    types: [ opened, reopened, edited, synchronize ]

jobs:
  E2E_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: action/setup-node@v2
        with:
          node-version: '12'
      - run: npm i -g protractor
      - run: nohup webdriver-manager start &
      - run: protractor conf.js
        working-directory: traffic_portal/test/end_to_end

